-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################

-- AUTOGENERATED HYPR CONFIG.

-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,

-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

--autogenerated = 1 # remove this line to remove the warning

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = 1,
	mirror = "DP-1",
})

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use

local terminal = "kitty"

local fileManager = "thunar"

local menu = "tofi-drun -c ~/.config/tofi/configA --drun-launch=true"

local browser = "firefox"

local notes = "obsidian"

local editor = "nvim"

local colorPicker = "hyprpicker"

local wallpaper_path = "~/Imagens/walls/a_lake_with_snow_covered_mountains_in_the_background.jpg"

-- --enable-features=UseOzonePlatform --ozone-platform=wayland use this flag to launch CEF/Electron apps in wayland

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:

-- topbar

-- wallpaper

-- clipboard

--it'll delete history at every restart

-- exec-once = $terminal

-- exec-once = nm-applet &

-- exec-once = waybar & hyprpaper & firefox

--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

-- Firefox

-- env = MOZ_ENABLE_WAYLAND,1

-- Nvidia

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("GBM_BACKEND", "nvidia-drm")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

-- remove if firefox crashes

hl.env("NVD_BACKEND", "direct")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

-- QT

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

hl.env("QT_STYLE_OVERRIDE", "kvantum")

-- Toolkit Backend Variables

hl.env("GDK_BACKEND", "wayland,x11,*")

hl.env("SDL_VIDEODRIVER", "wayland")

hl.env("CLUTTER_BACKEND", "wayland")

-- XDG Specifications

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
	general = {
		gaps_in = 0,
		gaps_out = 0,
		border_size = 2,
		-- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = true,
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "dwindle",
		col = {
			active_border = { colors = { "rgb(942124)", "rgb(ffffff)", "rgb(000000)", "rgb(000000)" }, angle = 45 },
			inactive_border = { colors = { "rgb(ffffff)", "rgb(000000)", "rgb(000000)", "rgb(000000)" }, angle = 45 },
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
	decoration = {
		rounding = 2,
		-- Change transparency of focused and unfocused windows
		active_opacity = 0.985,
		inactive_opacity = 0.985,
		-- https://wiki.hyprland.org/Configuring/Variables/#blur
		blur = {
			enabled = true,
			size = 2,
			passes = 1,
			new_optimizations = true,
			vibrancy = 0.1696,
			ignore_opacity = true,
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
	animations = {
		enabled = true,
		-- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
		-- bezier = myBezier, 0.05, 0.9, 0.1, 1.05
		-- animation = windows, 1, 7, myBezier
		-- animation = windowsOut, 1, 7, default, popin 80%
		-- animation = border, 1, 10, default
		-- animation = borderangle, 1, 8, default
		-- animation = fade, 1, 7, default
		-- animation = workspaces, 1, 6, default
	},
})

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
	dwindle = {
		preserve_split = true,
		-- You probably want this
	},
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
	misc = {
		force_default_wallpaper = 0,
		-- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true,
		-- If true disables the random hyprland logo / anime girl background. :(
		disable_splash_rendering = true,
		vrr = 0,
	},
})

hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
	input = {
		kb_layout = "custom",
		kb_variant = "br_ansi_fix",
		follow_mouse = 1,
		-- force_no_accel = 1
		sensitivity = 0,
		-- -1.0 - 1.0, 0 means no modification.
		touchpad = {
			natural_scroll = true,
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures

hl.config({
	gestures = {
		gesture = { 3, "horizontal", "workspace" },
	},
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

--###################

--## KEYBINDINGSS ###

--###################

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("firefox"))

hl.bind(mainMod .. " + " .. "O", hl.dsp.exec_cmd("obsidian"))

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("zeditor"))

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd("zeditor-alt"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "F", hl.dsp.exec_cmd("thunar"))

hl.bind(mainMod .. " + " .. "W", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "A", hl.dsp.exec_cmd("tofi-drun -c ~/.config/tofi/configA --drun-launch=true"))

-- bind = $mainMod, P, pseudo, # dwindle

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind("SUPER" .. " + " .. "E", hl.dsp.exec_cmd("jome -d| wl-copy"))

--Emojipicker + clipboard copy

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Move window position with mainMod + SHIFT + arrow keys

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "l" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "r" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "u" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "d" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

--bind = $mainMod, S, togglespecialworkspace, magic

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Move/resize windows + Mouse

hl.bind(mainMod .. " + " .. "X", hl.dsp.window.resize(nil), { mouse = true })

-- Resize windows with mainMod + CTRL + arrow keys

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod+Ctrl + Right", hl.dsp.resizeactive("30 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod+Ctrl + Left", hl.dsp.resizeactive("-30 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod+Ctrl + Up", hl.dsp.resizeactive("0 -30"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod+Ctrl + Down", hl.dsp.resizeactive("0 30"))

-- Clipboard

hl.bind(
	"SUPER" .. " + " .. "V",
	hl.dsp.exec_cmd("cliphist list| tofi -c ~/.config/tofi/configV| cliphist decode| wl-copy")
)

-- Colour Picker

hl.bind(mainMod .. " + " .. "P", hl.dsp.exec_cmd("hyprpicker| wl-copy"))

-- Screen locking

hl.bind("SUPER" .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

-- wlogout

hl.bind("SUPER" .. " + " .. "ESCAPE", hl.dsp.exec_cmd("wlogout"))

-- waybar

hl.bind("CTRL" .. " + " .. "Escape", hl.dsp.exec_cmd("killall waybar || waybar"))

-- toggle waybar

-- Screenshot

-- add --cursor flag to include cursor also, --freeze flag to freeze before selection

hl.bind("Print", hl.dsp.exec_cmd('export XDG_SCREENSHOTS_DIR="~/Imagens/prints" && grimblast --notify copysave screen'))

-- Entire screen + clipboard copy

hl.bind(
	"SUPER" .. " + " .. "Print",
	hl.dsp.exec_cmd('export XDG_SCREENSHOTS_DIR="~/Imagens/prints" && grimblast --notify copysave active')
)

-- current Active window only + clipboard copy

hl.bind(
	"ALT" .. " + " .. "Print",
	hl.dsp.exec_cmd('export XDG_SCREENSHOTS_DIR="~/Imagens/prints" && grimblast --notify copysave area')
)

-- Select area to take screenshot

-- Volume and Media Control

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 5"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 5"))

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pamixer --default-source -m"))

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer -t"))

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

-- Screen brightness

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s +5%"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 5%-"))

-- Wallpaper binds

hl.bind("SUPER+SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("~/.bin/wallpaper-wofi.sh"))

-- Recording

hl.bind(mainMod .. " + " .. "F9", hl.dsp.exec_cmd("~/.bin/record-toggle.sh"))

-- Screen Resolution Changer

hl.bind("SUPER+SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("~/.bin/res.sh"))

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

--# Use hyprctl clients to look for window class

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule v1

-- windowrule = float, ^(kitty)$

hl.window_rule({
	name = "windowrule-1",
	match = {
		class = "^(jome)$",
	},
	float = true,
})

-- Example windowrule v2

-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

hl.window_rule({
	name = "windowrule-2",
	match = {
		class = "^(Thorium-browser)$",
	},
	opacity = 0.90,
})

hl.window_rule({
	name = "windowrule-3",
	match = {
		class = "^(Code)$",
	},
	opacity = 0.80,
})

hl.window_rule({
	name = "windowrule-4",
	match = {
		class = "^(Arduino IDE)$",
	},
	opacity = 0.95,
})

hl.window_rule({
	name = "windowrule-5",
	match = {
		class = "^(dev.warp.Warp)$",
	},
	opacity = 0.95,
})

hl.window_rule({
	name = "windowrule-6",
	match = {
		class = "^(obsidian)$",
	},
	opacity = 0.95,
})

hl.window_rule({
	name = "windowrule-7",
	match = {
		class = "^(code-url-handler)$",
	},
	opacity = 0.95,
})

hl.window_rule({
	name = "windowrule-8",
	match = {
		class = "^(code-insiders-url-handler)$",
	},
	opacity = 0.95,
})

hl.window_rule({
	name = "windowrule-9",
	match = {
		class = "^(kitty)$",
	},
	opacity = 0.95,
})

hl.window_rule({
	name = "windowrule-10",
	match = {
		class = "^(org.gnome.Nautilus)$",
	},
	opacity = 0.95,
})

hl.window_rule({
	name = "windowrule-11",
	match = {
		class = "^(org.kde.ark)$",
	},
	opacity = 0.95,
	float = true,
})

hl.window_rule({
	name = "windowrule-12",
	match = {
		class = "^(nwg-look)$",
	},
	opacity = 0.95,
	float = true,
})

hl.window_rule({
	name = "windowrule-13",
	match = {
		class = "^(qt5ct)$",
	},
	opacity = 0.95,
	float = true,
})

hl.window_rule({
	name = "windowrule-14",
	match = {
		class = "^(qt6ct)$",
	},
	opacity = 0.95,
	float = true,
})

hl.window_rule({
	name = "windowrule-15",
	match = {
		class = "^(kvantummanager)$",
	},
	opacity = 0.95,
	float = true,
})

hl.window_rule({
	name = "windowrule-16",
	match = {
		class = "^(pavucontrol)$",
	},
	opacity = 0.95,
	float = true,
})

hl.window_rule({
	name = "windowrule-17",
	match = {
		class = "^(blueman-manager)$",
	},
	opacity = 0.95,
	float = true,
})

hl.window_rule({
	name = "windowrule-18",
	match = {
		class = "^(nm-applet)$",
	},
	opacity = 0.95,
	float = true,
})

hl.window_rule({
	name = "windowrule-19",
	match = {
		class = "^(Spotify)$",
	},
	opacity = 0.95,
})

hl.window_rule({
	name = "windowrule-20",
	match = {
		initial_title = "^(Spotify Free)$",
	},
	opacity = 0.95,
})

hl.window_rule({
	name = "windowrule-21",
	match = {
		class = "^(nm-connection-editor)$",
	},
	opacity = 0.95,
	float = true,
})

hl.window_rule({
	name = "windowrule-22",
	match = {
		class = "^(org.kde.polkit-kde-authentication-agent-1)$",
	},
	opacity = 0.95,
	float = true,
})

hl.window_rule({
	name = "windowrule-23",
	match = {
		class = "^(polkit-gnome-authentication-agent-1)$",
	},
	opacity = 0.95,
})

hl.window_rule({
	name = "windowrule-24",
	match = {
		class = "^(org.freedesktop.impl.portal.desktop.gtk)$",
	},
	opacity = 0.95,
})

hl.window_rule({
	name = "windowrule-25",
	match = {
		class = "^(org.freedesktop.impl.portal.desktop.hyprland)$",
	},
	opacity = 0.95,
})

hl.window_rule({
	name = "windowrule-26",
	match = {
		class = "^(vesktop)$",
	},
	opacity = 0.95,
})

-- windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

-- layerrule = blur,waybar

hl.layer_rule({
	match = {
		namespace = "tofi",
	},
	ignore_alpha = 0,
})

hl.layer_rule({
	match = {
		namespace = "dunst",
	},
	ignore_alpha = 0,
	blur = true,
})

hl.window_rule({
	name = "no_blur_1",
	match = {
		title = "^(deadlocked_overlay)$",
	},
	-- TODO: review rule: "no_blur 1"
})

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("/usr/bin/dunst")
	hl.exec_cmd("waybar")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd(
		'awww img "~/Imagens/walls/a_lake_with_snow_covered_mountains_in_the_background.jpg" --transition-fps 255 --transition-type outer --transition-duration 0.8'
	)
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd('rm "' .. os.getenv("HOME") .. '/.cache/cliphist/db"')
	hl.exec_cmd("hypridle")
	hl.exec_cmd(
		"dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE"
	)
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland")
	hl.exec_cmd("/usr/lib/xdg-desktop-portal")
end)
